package com.fable.insightview.monitor.alarmmgr.alarmDispatchFilter.mapper;

import com.fable.insightview.monitor.alarmmgr.alarmDispatchFilter.entity.AlarmDispatchFilter;
import com.fable.insightview.monitor.alarmmgr.alarmDispatchFilter.entity.AlarmDispatchFilterDef;
import com.fable.insightview.monitor.alarmmgr.alarmDispatchFilter.entity.AlarmDispatchFilterDefExample;
import com.fable.insightview.monitor.alarmmgr.alarmDispatchFilter.entity.AlarmDispatchFilterExample;
import com.fable.insightview.monitor.alarmmgr.entity.AlarmEventDefineBean;
import com.fable.insightview.monitor.alarmmgr.entity.AlarmLevelInfo;
import com.fable.insightview.monitor.alarmmgr.entity.AlarmTypeInfo;
import com.fable.insightview.monitor.alarmmgr.entity.MOSourceBean;
import com.fable.insightview.platform.page.Page;

import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AlarmDispatchFilterDefMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Alarm_Dispatch_Filter_Def
     *
     * @mbggenerated Fri Jun 12 17:27:14 GMT+08:00 2015
     */
    int countByExample(AlarmDispatchFilterDefExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Alarm_Dispatch_Filter_Def
     *
     * @mbggenerated Fri Jun 12 17:27:14 GMT+08:00 2015
     */
    int deleteByExample(AlarmDispatchFilterDefExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Alarm_Dispatch_Filter_Def
     *
     * @mbggenerated Fri Jun 12 17:27:14 GMT+08:00 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Alarm_Dispatch_Filter_Def
     *
     * @mbggenerated Fri Jun 12 17:27:14 GMT+08:00 2015
     */
    int insert(AlarmDispatchFilterDef record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Alarm_Dispatch_Filter_Def
     *
     * @mbggenerated Fri Jun 12 17:27:14 GMT+08:00 2015
     */
    int insertSelective(AlarmDispatchFilterDef record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Alarm_Dispatch_Filter_Def
     *
     * @mbggenerated Fri Jun 12 17:27:14 GMT+08:00 2015
     */
    List<AlarmDispatchFilterDef> selectByExample(AlarmDispatchFilterDefExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Alarm_Dispatch_Filter_Def
     *
     * @mbggenerated Fri Jun 12 17:27:14 GMT+08:00 2015
     */
    AlarmDispatchFilterDef selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Alarm_Dispatch_Filter_Def
     *
     * @mbggenerated Fri Jun 12 17:27:14 GMT+08:00 2015
     */
    int updateByExampleSelective(@Param("record") AlarmDispatchFilterDef record, @Param("example") AlarmDispatchFilterDefExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Alarm_Dispatch_Filter_Def
     *
     * @mbggenerated Fri Jun 12 17:27:14 GMT+08:00 2015
     */
    int updateByExample(@Param("record") AlarmDispatchFilterDef record, @Param("example") AlarmDispatchFilterDefExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Alarm_Dispatch_Filter_Def
     *
     * @mbggenerated Fri Jun 12 17:27:14 GMT+08:00 2015
     */
    int updateByPrimaryKeySelective(AlarmDispatchFilterDef record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Alarm_Dispatch_Filter_Def
     *
     * @mbggenerated Fri Jun 12 17:27:14 GMT+08:00 2015
     */
    int updateByPrimaryKey(AlarmDispatchFilterDef record);
    
    List<AlarmDispatchFilterDef> selectByExampleLimit(AlarmDispatchFilterDefExample example);
    
    /**
	 * 查询告警级别
	 * 
	 * @return
	 */
	List<AlarmLevelInfo> queryAlarmLevelList(Page<AlarmLevelInfo> page);

	/**
	 * 过滤条件：查询告警类型
	 * 
	 * @return
	 */
	List<AlarmTypeInfo> queryAlarmTypeList(Page<AlarmTypeInfo> page);

	/**
	 * 查询所有告警源对象
	 * 
	 * @return
	 */
	List<MOSourceBean> queryMOSourceList(Page<MOSourceBean> page);

	/**
	 * 过滤查询告警事件
	 * 
	 * @return
	 */
	List<AlarmEventDefineBean> queryEventList(Page<AlarmEventDefineBean> page);
}