package com.fable.insightview.monitor.alarmmgr.alarmDispatchFilter.entity;

import java.util.ArrayList;
import java.util.List;

public class AlarmDispatchFilterExample {
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database table Alarm_Dispatch_Filter
	 * 
	 * @mbggenerated Thu May 21 09:52:14 GMT+08:00 2015
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database table Alarm_Dispatch_Filter
	 * 
	 * @mbggenerated Thu May 21 09:52:14 GMT+08:00 2015
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database table Alarm_Dispatch_Filter
	 * 
	 * @mbggenerated Thu May 21 09:52:14 GMT+08:00 2015
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table Alarm_Dispatch_Filter
	 * 
	 * @mbggenerated Thu May 21 09:52:14 GMT+08:00 2015
	 */
	public AlarmDispatchFilterExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	protected Integer page;
	protected Integer rows;

	public Integer getPage() {
		return page;
	}

	public void setPage(Integer page) {
		this.page = page;
	}

	public Integer getRows() {
		return rows;
	}

	public void setRows(Integer rows) {
		this.rows = rows;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table Alarm_Dispatch_Filter
	 * 
	 * @mbggenerated Thu May 21 09:52:14 GMT+08:00 2015
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table Alarm_Dispatch_Filter
	 * 
	 * @mbggenerated Thu May 21 09:52:14 GMT+08:00 2015
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table Alarm_Dispatch_Filter
	 * 
	 * @mbggenerated Thu May 21 09:52:14 GMT+08:00 2015
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table Alarm_Dispatch_Filter
	 * 
	 * @mbggenerated Thu May 21 09:52:14 GMT+08:00 2015
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table Alarm_Dispatch_Filter
	 * 
	 * @mbggenerated Thu May 21 09:52:14 GMT+08:00 2015
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table Alarm_Dispatch_Filter
	 * 
	 * @mbggenerated Thu May 21 09:52:14 GMT+08:00 2015
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table Alarm_Dispatch_Filter
	 * 
	 * @mbggenerated Thu May 21 09:52:14 GMT+08:00 2015
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table Alarm_Dispatch_Filter
	 * 
	 * @mbggenerated Thu May 21 09:52:14 GMT+08:00 2015
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table Alarm_Dispatch_Filter
	 * 
	 * @mbggenerated Thu May 21 09:52:14 GMT+08:00 2015
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table Alarm_Dispatch_Filter
	 * 
	 * @mbggenerated Thu May 21 09:52:14 GMT+08:00 2015
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to
	 * the database table Alarm_Dispatch_Filter
	 * 
	 * @mbggenerated Thu May 21 09:52:14 GMT+08:00 2015
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("ID is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("ID is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Integer value) {
			addCriterion("ID =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Integer value) {
			addCriterion("ID <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Integer value) {
			addCriterion("ID >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("ID >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(Integer value) {
			addCriterion("ID <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(Integer value) {
			addCriterion("ID <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Integer> values) {
			addCriterion("ID in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Integer> values) {
			addCriterion("ID not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Integer value1, Integer value2) {
			addCriterion("ID between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Integer value1, Integer value2) {
			addCriterion("ID not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andFilterIdIsNull() {
			addCriterion("FilterID is null");
			return (Criteria) this;
		}

		public Criteria andFilterIdIsNotNull() {
			addCriterion("FilterID is not null");
			return (Criteria) this;
		}

		public Criteria andFilterIdEqualTo(Integer value) {
			addCriterion("FilterID =", value, "filterId");
			return (Criteria) this;
		}

		public Criteria andFilterIdNotEqualTo(Integer value) {
			addCriterion("FilterID <>", value, "filterId");
			return (Criteria) this;
		}

		public Criteria andFilterIdGreaterThan(Integer value) {
			addCriterion("FilterID >", value, "filterId");
			return (Criteria) this;
		}

		public Criteria andFilterIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("FilterID >=", value, "filterId");
			return (Criteria) this;
		}

		public Criteria andFilterIdLessThan(Integer value) {
			addCriterion("FilterID <", value, "filterId");
			return (Criteria) this;
		}

		public Criteria andFilterIdLessThanOrEqualTo(Integer value) {
			addCriterion("FilterID <=", value, "filterId");
			return (Criteria) this;
		}

		public Criteria andFilterIdIn(List<Integer> values) {
			addCriterion("FilterID in", values, "filterId");
			return (Criteria) this;
		}

		public Criteria andFilterIdNotIn(List<Integer> values) {
			addCriterion("FilterID not in", values, "filterId");
			return (Criteria) this;
		}

		public Criteria andFilterIdBetween(Integer value1, Integer value2) {
			addCriterion("FilterID between", value1, value2, "filterId");
			return (Criteria) this;
		}

		public Criteria andFilterIdNotBetween(Integer value1, Integer value2) {
			addCriterion("FilterID not between", value1, value2, "filterId");
			return (Criteria) this;
		}

		public Criteria andFilterKeyIsNull() {
			addCriterion("FilterKey is null");
			return (Criteria) this;
		}

		public Criteria andFilterKeyIsNotNull() {
			addCriterion("FilterKey is not null");
			return (Criteria) this;
		}

		public Criteria andFilterKeyEqualTo(String value) {
			addCriterion("FilterKey =", value, "filterKey");
			return (Criteria) this;
		}

		public Criteria andFilterKeyNotEqualTo(String value) {
			addCriterion("FilterKey <>", value, "filterKey");
			return (Criteria) this;
		}

		public Criteria andFilterKeyGreaterThan(String value) {
			addCriterion("FilterKey >", value, "filterKey");
			return (Criteria) this;
		}

		public Criteria andFilterKeyGreaterThanOrEqualTo(String value) {
			addCriterion("FilterKey >=", value, "filterKey");
			return (Criteria) this;
		}

		public Criteria andFilterKeyLessThan(String value) {
			addCriterion("FilterKey <", value, "filterKey");
			return (Criteria) this;
		}

		public Criteria andFilterKeyLessThanOrEqualTo(String value) {
			addCriterion("FilterKey <=", value, "filterKey");
			return (Criteria) this;
		}

		public Criteria andFilterKeyLike(String value) {
			addCriterion("FilterKey like", value, "filterKey");
			return (Criteria) this;
		}

		public Criteria andFilterKeyNotLike(String value) {
			addCriterion("FilterKey not like", value, "filterKey");
			return (Criteria) this;
		}

		public Criteria andFilterKeyIn(List<String> values) {
			addCriterion("FilterKey in", values, "filterKey");
			return (Criteria) this;
		}

		public Criteria andFilterKeyNotIn(List<String> values) {
			addCriterion("FilterKey not in", values, "filterKey");
			return (Criteria) this;
		}

		public Criteria andFilterKeyBetween(String value1, String value2) {
			addCriterion("FilterKey between", value1, value2, "filterKey");
			return (Criteria) this;
		}

		public Criteria andFilterKeyNotBetween(String value1, String value2) {
			addCriterion("FilterKey not between", value1, value2, "filterKey");
			return (Criteria) this;
		}

		public Criteria andFilterKeyValueIsNull() {
			addCriterion("FilterKeyValue is null");
			return (Criteria) this;
		}

		public Criteria andFilterKeyValueIsNotNull() {
			addCriterion("FilterKeyValue is not null");
			return (Criteria) this;
		}

		public Criteria andFilterKeyValueEqualTo(Integer value) {
			addCriterion("FilterKeyValue =", value, "filterKeyValue");
			return (Criteria) this;
		}

		public Criteria andFilterKeyValueNotEqualTo(Integer value) {
			addCriterion("FilterKeyValue <>", value, "filterKeyValue");
			return (Criteria) this;
		}

		public Criteria andFilterKeyValueGreaterThan(Integer value) {
			addCriterion("FilterKeyValue >", value, "filterKeyValue");
			return (Criteria) this;
		}

		public Criteria andFilterKeyValueGreaterThanOrEqualTo(Integer value) {
			addCriterion("FilterKeyValue >=", value, "filterKeyValue");
			return (Criteria) this;
		}

		public Criteria andFilterKeyValueLessThan(Integer value) {
			addCriterion("FilterKeyValue <", value, "filterKeyValue");
			return (Criteria) this;
		}

		public Criteria andFilterKeyValueLessThanOrEqualTo(Integer value) {
			addCriterion("FilterKeyValue <=", value, "filterKeyValue");
			return (Criteria) this;
		}

		public Criteria andFilterKeyValueIn(List<Integer> values) {
			addCriterion("FilterKeyValue in", values, "filterKeyValue");
			return (Criteria) this;
		}

		public Criteria andFilterKeyValueNotIn(List<Integer> values) {
			addCriterion("FilterKeyValue not in", values, "filterKeyValue");
			return (Criteria) this;
		}

		public Criteria andFilterKeyValueBetween(Integer value1, Integer value2) {
			addCriterion("FilterKeyValue between", value1, value2, "filterKeyValue");
			return (Criteria) this;
		}

		public Criteria andFilterKeyValueNotBetween(Integer value1, Integer value2) {
			addCriterion("FilterKeyValue not between", value1, value2, "filterKeyValue");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to
	 * the database table Alarm_Dispatch_Filter
	 * 
	 * @mbggenerated Thu May 21 09:52:14 GMT+08:00 2015
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to
	 * the database table Alarm_Dispatch_Filter
	 * 
	 * @mbggenerated do_not_delete_during_merge Wed May 20 15:26:11 GMT+08:00
	 *               2015
	 */
	public static class Criteria extends GeneratedCriteria {

		protected Criteria() {
			super();
		}
	}
}