package com.fable.insightview.monitor.alarmmgr.alarmDispatchFilter.entity;

import com.fable.insightview.platform.core.dao.idgenerator.NumberGenerator;

public class AlarmDispatchFilter {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Alarm_Dispatch_Filter.ID
	 * @mbggenerated  Thu May 21 09:52:14 GMT+08:00 2015
	 */
	@NumberGenerator(name = "SNMPCommunityTempPK")
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Alarm_Dispatch_Filter.Filter_ID
	 * @mbggenerated  Thu May 21 09:52:14 GMT+08:00 2015
	 */
	private Integer filterId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Alarm_Dispatch_Filter.Filter_Key
	 * @mbggenerated  Thu May 21 09:52:14 GMT+08:00 2015
	 */
	private String filterKey;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Alarm_Dispatch_Filter.Filter_Key_Value
	 * @mbggenerated  Thu May 21 09:52:14 GMT+08:00 2015
	 */
	private Integer filterKeyValue;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Alarm_Dispatch_Filter.Filter_Key_Value_Name
	 * @mbggenerated  Thu May 21 09:52:14 GMT+08:00 2015
	 */
	private String filterKeyValueName;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Alarm_Dispatch_Filter.ID
	 * @return  the value of Alarm_Dispatch_Filter.ID
	 * @mbggenerated  Thu May 21 09:52:14 GMT+08:00 2015
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Alarm_Dispatch_Filter.ID
	 * @param id  the value for Alarm_Dispatch_Filter.ID
	 * @mbggenerated  Thu May 21 09:52:14 GMT+08:00 2015
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Alarm_Dispatch_Filter.Filter_ID
	 * @return  the value of Alarm_Dispatch_Filter.Filter_ID
	 * @mbggenerated  Thu May 21 09:52:14 GMT+08:00 2015
	 */
	public Integer getFilterId() {
		return filterId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Alarm_Dispatch_Filter.Filter_ID
	 * @param filterId  the value for Alarm_Dispatch_Filter.Filter_ID
	 * @mbggenerated  Thu May 21 09:52:14 GMT+08:00 2015
	 */
	public void setFilterId(Integer filterId) {
		this.filterId = filterId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Alarm_Dispatch_Filter.Filter_Key
	 * @return  the value of Alarm_Dispatch_Filter.Filter_Key
	 * @mbggenerated  Thu May 21 09:52:14 GMT+08:00 2015
	 */
	public String getFilterKey() {
		return filterKey;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Alarm_Dispatch_Filter.Filter_Key
	 * @param filterKey  the value for Alarm_Dispatch_Filter.Filter_Key
	 * @mbggenerated  Thu May 21 09:52:14 GMT+08:00 2015
	 */
	public void setFilterKey(String filterKey) {
		this.filterKey = filterKey == null ? null : filterKey.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Alarm_Dispatch_Filter.Filter_Key_Value
	 * @return  the value of Alarm_Dispatch_Filter.Filter_Key_Value
	 * @mbggenerated  Thu May 21 09:52:14 GMT+08:00 2015
	 */
	public Integer getFilterKeyValue() {
		return filterKeyValue;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Alarm_Dispatch_Filter.Filter_Key_Value
	 * @param filterKeyValue  the value for Alarm_Dispatch_Filter.Filter_Key_Value
	 * @mbggenerated  Thu May 21 09:52:14 GMT+08:00 2015
	 */
	public void setFilterKeyValue(Integer filterKeyValue) {
		this.filterKeyValue = filterKeyValue;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Alarm_Dispatch_Filter.Filter_Key_Value_Name
	 * @return  the value of Alarm_Dispatch_Filter.Filter_Key_Value_Name
	 * @mbggenerated  Thu May 21 09:52:14 GMT+08:00 2015
	 */
	public String getFilterKeyValueName() {
		return filterKeyValueName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Alarm_Dispatch_Filter.Filter_Key_Value_Name
	 * @param filterKeyValueName  the value for Alarm_Dispatch_Filter.Filter_Key_Value_Name
	 * @mbggenerated  Thu May 21 09:52:14 GMT+08:00 2015
	 */
	public void setFilterKeyValueName(String filterKeyValueName) {
		this.filterKeyValueName = filterKeyValueName == null ? null : filterKeyValueName.trim();
	}
}