package com.fable.insightview.monitor.alarmmgr.alarmDispatchFilter.entity;

import com.fable.insightview.platform.core.dao.idgenerator.NumberGenerator;

public class AlarmDispatchFilterDef {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Alarm_Dispatch_Filter_Def.ID
     *
     * @mbggenerated Fri Jun 12 17:27:14 GMT+08:00 2015
     */
	@NumberGenerator(name = "SNMPCommunityTempPK")
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Alarm_Dispatch_Filter_Def.Filter_Name
     *
     * @mbggenerated Fri Jun 12 17:27:14 GMT+08:00 2015
     */
    private String filterName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Alarm_Dispatch_Filter_Def.Is_Default
     *
     * @mbggenerated Fri Jun 12 17:27:14 GMT+08:00 2015
     */
    private Short isDefault;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Alarm_Dispatch_Filter_Def.Descr
     *
     * @mbggenerated Fri Jun 12 17:27:14 GMT+08:00 2015
     */
    private String descr;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Alarm_Dispatch_Filter_Def.ID
     *
     * @return the value of Alarm_Dispatch_Filter_Def.ID
     *
     * @mbggenerated Fri Jun 12 17:27:14 GMT+08:00 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Alarm_Dispatch_Filter_Def.ID
     *
     * @param id the value for Alarm_Dispatch_Filter_Def.ID
     *
     * @mbggenerated Fri Jun 12 17:27:14 GMT+08:00 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Alarm_Dispatch_Filter_Def.Filter_Name
     *
     * @return the value of Alarm_Dispatch_Filter_Def.Filter_Name
     *
     * @mbggenerated Fri Jun 12 17:27:14 GMT+08:00 2015
     */
    public String getFilterName() {
        return filterName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Alarm_Dispatch_Filter_Def.Filter_Name
     *
     * @param filterName the value for Alarm_Dispatch_Filter_Def.Filter_Name
     *
     * @mbggenerated Fri Jun 12 17:27:14 GMT+08:00 2015
     */
    public void setFilterName(String filterName) {
        this.filterName = filterName == null ? null : filterName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Alarm_Dispatch_Filter_Def.Is_Default
     *
     * @return the value of Alarm_Dispatch_Filter_Def.Is_Default
     *
     * @mbggenerated Fri Jun 12 17:27:14 GMT+08:00 2015
     */
    public Short getIsDefault() {
        return isDefault;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Alarm_Dispatch_Filter_Def.Is_Default
     *
     * @param isDefault the value for Alarm_Dispatch_Filter_Def.Is_Default
     *
     * @mbggenerated Fri Jun 12 17:27:14 GMT+08:00 2015
     */
    public void setIsDefault(Short isDefault) {
        this.isDefault = isDefault;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Alarm_Dispatch_Filter_Def.Descr
     *
     * @return the value of Alarm_Dispatch_Filter_Def.Descr
     *
     * @mbggenerated Fri Jun 12 17:27:14 GMT+08:00 2015
     */
    public String getDescr() {
        return descr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Alarm_Dispatch_Filter_Def.Descr
     *
     * @param descr the value for Alarm_Dispatch_Filter_Def.Descr
     *
     * @mbggenerated Fri Jun 12 17:27:14 GMT+08:00 2015
     */
    public void setDescr(String descr) {
        this.descr = descr == null ? null : descr.trim();
    }
}